server:
  port: 7001

spring:
  application:
    name: zuul-gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
          defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 1
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

zuul:
  ignored-services: '*'
  routes:
    forex-rates-service:
      path: /redis-demo/**
      serviceId: redis-demo-service

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000
  ServerListRefreshInterval: 3000

