spring:

#MYSQL config
  datasource:
    url: jdbc:mysql://localhost:3306/redis_demo?createDatabaseIfNotExist=true
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  #Redis cache config
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:

  application:
    name: redis-demo-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

server:
  port: 9001
